# Generated by Django 4.2.4 on 2023-09-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CamposTipopubli",
            fields=[
                ("idcampo", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nombrecampo",
                    models.CharField(db_column="nombreCampo", max_length=45),
                ),
            ],
            options={
                "db_table": "campos_tipopubli",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CamposTipopubliHasTipoPublicaciones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "campos_tipopubli_has_tipo_publicaciones",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Comentarios",
            fields=[
                ("id_comentario", models.AutoField(primary_key=True, serialize=False)),
                ("comentario", models.CharField(max_length=100)),
                ("fechacom", models.DateField()),
            ],
            options={
                "db_table": "comentarios",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Mascotas",
            fields=[
                ("id_mascota", models.AutoField(primary_key=True, serialize=False)),
                ("nombremas", models.CharField(max_length=45)),
                ("raza", models.CharField(max_length=45)),
                ("sexo", models.CharField(max_length=45)),
                ("accesorios", models.CharField(blank=True, max_length=45, null=True)),
                ("tamano", models.CharField(max_length=45)),
                ("edad", models.IntegerField(blank=True, null=True)),
                ("caracteristicas", models.CharField(max_length=45)),
            ],
            options={
                "db_table": "mascotas",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Publicaciones",
            fields=[
                ("id_publicacion", models.AutoField(primary_key=True, serialize=False)),
                ("estado", models.CharField(max_length=45)),
                ("fecha", models.DateField()),
            ],
            options={
                "db_table": "publicaciones",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PublicacionesCamposTipopubliTipoPublicaciones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "publicaciones_campos_tipopubli_tipo_publicaciones",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SaludMascota",
            fields=[
                ("idestado_salud", models.AutoField(primary_key=True, serialize=False)),
                ("enfermedades", models.CharField(max_length=60)),
                ("vacunas", models.CharField(max_length=60)),
                ("esterilizacion", models.CharField(max_length=20)),
                ("medicamentos", models.CharField(max_length=60)),
            ],
            options={
                "db_table": "salud_mascota",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TipoPublicaciones",
            fields=[
                ("idtipo_publi", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nombretipopubli",
                    models.CharField(db_column="nombreTipoPubli", max_length=45),
                ),
            ],
            options={
                "db_table": "tipo_publicaciones",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Usuarios",
            fields=[
                ("id_usuario", models.AutoField(primary_key=True, serialize=False)),
                ("nombreusu", models.CharField(max_length=60)),
                ("apellidousu", models.CharField(max_length=60)),
                ("documento", models.IntegerField(unique=True)),
                ("correousu", models.CharField(max_length=60, unique=True)),
                ("telefono", models.IntegerField()),
                ("localidad", models.CharField(max_length=60)),
                ("barrio", models.CharField(max_length=60)),
                ("contrasena", models.CharField(max_length=60)),
            ],
            options={
                "db_table": "usuarios",
                "managed": False,
            },
        ),
    ]
