# Generated by Django 4.2.4 on 2023-12-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="telefono",
            field=models.BigIntegerField(),
        ),
    ]
