# Generated by Django 3.2.12 on 2023-12-07 15:51

from django.db import migrations, models
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imagen',
            field=models.ImageField(default='img/fotoperfil.jpg', upload_to=usuarios.models.Perfil.get_upload_path),
        ),
    ]
