# Generated by Django 4.2.4 on 2023-09-25 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0002_campostipopubli_tipopublicaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('nombremas', models.CharField(max_length=45)),
                ('especie', models.CharField(max_length=45)),
                ('raza', models.CharField(max_length=45)),
                ('sexo', models.CharField(max_length=45)),
                ('color', models.CharField(max_length=45)),
                ('accesorios', models.CharField(blank=True, max_length=45, null=True)),
                ('tamano', models.CharField(max_length=45)),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('caracteristicas', models.CharField(max_length=45)),
                ('img1', models.ImageField(upload_to='imgmascotas')),
                ('img2', models.ImageField(upload_to='imgmascotas')),
                ('img3', models.ImageField(upload_to='imgmascotas')),
                ('img4', models.ImageField(upload_to='imgmascotas')),
                ('img5', models.ImageField(upload_to='imgmascotas')),
            ],
            options={
                'db_table': 'mascotas',
            },
        ),
        migrations.CreateModel(
            name='SaludMascota',
            fields=[
                ('idestado_salud', models.AutoField(primary_key=True, serialize=False)),
                ('enfermedades', models.CharField(max_length=60)),
                ('vacunas', models.CharField(max_length=60)),
                ('esterilizacion', models.BooleanField(default=False)),
                ('medicamentos', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'salud_mascota',
            },
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='apellidousu',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='contrasena',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='correousu',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombreusu',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id_publicacion', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('id_mascota', models.OneToOneField(db_column='id_mascota', on_delete=django.db.models.deletion.CASCADE, to='usuarios.mascota')),
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
                ('idestado_salud', models.OneToOneField(db_column='idestado_salud', null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.saludmascota')),
            ],
            options={
                'db_table': 'publicaciones',
            },
        ),
        migrations.AddField(
            model_name='mascota',
            name='id_usuario',
            field=models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario', verbose_name='id_dueño'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='idestado_salud',
            field=models.OneToOneField(db_column='idestado_salud', on_delete=django.db.models.deletion.CASCADE, to='usuarios.saludmascota'),
        ),
    ]
