# Generated by Django 3.2.12 on 2023-12-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_perfil_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='accesoriosmas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='marcasmas',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
