# Generated by Django 4.2.4 on 2023-09-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0002_alter_usuario_managers_remove_usuario_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="latitud",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="longitud",
            field=models.FloatField(null=True),
        ),
    ]
