# Generated by Django 4.2.4 on 2023-11-27 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_publicacionesfavoritas_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascotasadopcion',
            name='barrioAdopcion',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='mascotasadopcion',
            name='localidadAdopcion',
            field=models.CharField(default='', max_length=60),
        ),
    ]
