# Generated by Django 3.2.12 on 2023-12-09 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20231209_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.CharField(max_length=500)),
                ('fechacom', models.DateTimeField(auto_now_add=True)),
                ('id_publicacion', models.ForeignKey(db_column='id_publicacion', on_delete=django.db.models.deletion.CASCADE, to='usuarios.publicacion')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comentarios',
            },
        ),
    ]
