# Generated by Django 4.2.4 on 2023-09-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0003_usuario_latitud_usuario_longitud"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="barrio",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="localidad",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="username",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
