# Generated by Django 4.2.4 on 2023-11-28 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_mascotasadopcion_barrioadopcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='fechaPublicacion',
            field=models.DateField(auto_now=True),
        ),
    ]
