# Generated by Django 4.2.4 on 2023-09-25 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_mascota_saludmascota_remove_usuario_apellidousu_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CamposTipopubli',
            new_name='CamposPubli',
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='accesorios',
            new_name='accesoriosmas',
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='caracteristicas',
            new_name='caracteristicasmas',
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='color',
            new_name='colormas',
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='edad',
            new_name='edadmas',
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='especie',
            new_name='especiemas',
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='raza',
            new_name='razamas',
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='sexo',
            new_name='sexomas',
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='tamano',
            new_name='tamanomas',
        ),
        migrations.RenameField(
            model_name='saludmascota',
            old_name='enfermedades',
            new_name='enfermedadesmas',
        ),
        migrations.RenameField(
            model_name='saludmascota',
            old_name='esterilizacion',
            new_name='esterilizacionmas',
        ),
        migrations.RenameField(
            model_name='saludmascota',
            old_name='medicamentos',
            new_name='medicamentosmas',
        ),
        migrations.RenameField(
            model_name='saludmascota',
            old_name='vacunas',
            new_name='vacunasmas',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='recompensa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='campospubli',
            table='camposPubli',
        ),
    ]
