# Generated by Django 4.2.4 on 2023-09-25 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_rename_campostipopubli_campospubli_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='caracteristicasmas',
            new_name='marcasmas',
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='tamanomas',
            new_name='tamañomas',
        ),
    ]
