# Generated by Django 3.2.12 on 2023-11-30 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_publicacion_fechapublicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='edadmas',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
