# Generated by Django 3.2.12 on 2023-12-10 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fechacom',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
