# Generated by Django 4.2.4 on 2023-09-26 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_rename_caracteristicasmas_mascota_marcasmas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario', verbose_name='id_dueño'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
    ]
