# Generated by Django 3.2.12 on 2023-12-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_comentario_fechacom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.CharField(max_length=400),
        ),
    ]
