# Generated by Django 4.2.4 on 2023-09-27 15:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_mascota_id_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MascotasAdopcion',
            fields=[
                ('publicacion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.publicacion')),
                ('motivoAdopcion', models.CharField(max_length=200)),
                ('requisitosAdopcion', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'mascotas_adopcion',
            },
            bases=('usuarios.publicacion',),
        ),
        migrations.DeleteModel(
            name='CamposPubli',
        ),
        migrations.RenameField(
            model_name='publicacion',
            old_name='estado',
            new_name='estadoPubli',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='recompensa',
        ),
        migrations.AddField(
            model_name='mascota',
            name='entrenamientomas',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='personalidadmas',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='mascota',
            name='socializacionmas',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='fechaPubli',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='colormas',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='especiemas',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='marcasmas',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='razamas',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='sexomas',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='tamañomas',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='saludmascota',
            name='enfermedadesmas',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='saludmascota',
            name='esterilizacionmas',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='saludmascota',
            name='medicamentosmas',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='saludmascota',
            name='vacunasmas',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='MascotasEncontradas',
            fields=[
                ('publicacion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.publicacion')),
                ('localidadEncuentro', models.CharField(max_length=60)),
                ('barrioEncuentro', models.CharField(max_length=60)),
                ('recompensa', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mascotas_encontradas',
            },
            bases=('usuarios.publicacion',),
        ),
        migrations.CreateModel(
            name='MascotasPerdidas',
            fields=[
                ('publicacion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.publicacion')),
                ('localidadExtravio', models.CharField(max_length=60)),
                ('barrioExtravio', models.CharField(max_length=60)),
                ('recompensa', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mascotas_perdidas',
            },
            bases=('usuarios.publicacion',),
        ),
    ]
