# Generated by Django 4.2.4 on 2023-09-27 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_mascotasadopcion_delete_campospubli_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascotasencontradas',
            name='fechaEncuentro',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='mascotasperdidas',
            name='fechaExtravio',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='fechaPubli',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
