# Generated by Django 4.2.4 on 2023-09-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_mascotasencontradas_fechaencuentro_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoPublicaciones',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='apartado',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='saludmascota',
            name='vacunasmas',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
