# Generated by Django 4.2.4 on 2023-11-01 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_delete_tipopublicaciones_publicacion_apartado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='idestado_salud',
            field=models.ForeignKey(db_column='idestado_salud', on_delete=django.db.models.deletion.CASCADE, to='usuarios.saludmascota'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='idestado_salud',
            field=models.ForeignKey(db_column='idestado_salud', null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.saludmascota'),
        ),
    ]
