# Generated by Django 3.2.12 on 2023-11-07 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_mascota_idestado_salud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='img1',
            field=models.ImageField(null=True, upload_to='imgmascotas'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='img2',
            field=models.ImageField(null=True, upload_to='imgmascotas'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='img3',
            field=models.ImageField(null=True, upload_to='imgmascotas'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='img4',
            field=models.ImageField(null=True, upload_to='imgmascotas'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='img5',
            field=models.ImageField(null=True, upload_to='imgmascotas'),
        ),
    ]
