# Generated by Django 3.2.12 on 2023-11-15 05:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_auto_20231106_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascotasperdidas',
            name='horaExtravio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='img1',
            field=models.ImageField(default='', upload_to='imgmascotas'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='img2',
            field=models.ImageField(default='', upload_to='imgmascotas'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='img3',
            field=models.ImageField(default='', upload_to='imgmascotas'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='img4',
            field=models.ImageField(default='', upload_to='imgmascotas'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='img5',
            field=models.ImageField(default='', upload_to='imgmascotas'),
        ),
        migrations.AlterField(
            model_name='mascotasperdidas',
            name='fechaExtravio',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.CharField(max_length=100)),
                ('fechacom', models.DateTimeField()),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'db_table': 'comentarios',
            },
        ),
    ]
