# Generated by Django 3.2.12 on 2023-11-20 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_mascotasencontradas_horaextravio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascotasencontradas',
            old_name='horaExtravio',
            new_name='horaEncuentro',
        ),
    ]
