# Generated by Django 4.2.4 on 2023-11-20 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_rename_horaextravio_mascotasencontradas_horaencuentro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='nombremas',
            field=models.CharField(max_length=45, null='True'),
        ),
    ]
