# Generated by Django 4.2.4 on 2023-11-20 23:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_alter_mascota_nombremas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascotasencontradas',
            name='fechaEncuentro',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
