function cargarBarrios() {
    var localidades = document.getElementById("localidades");
    var barrios = document.getElementById("barrios");
    var seleccionLocalidad = localidades.value;

    // Limpiar el select de barrios antes de cargar nuevos elementos
    barrios.innerHTML = "";

    if (seleccionLocalidad === "Usaquén") {
      var barriosUsaquen = [
        "Canaima",
        "La Floresta de La Sabana",
        "Torca",
        "Altos de Serrezuela",
        "Balcones de Vista Hermosa",
        "Balmoral Norte",
        "Buenavista",
        "Chaparral",
        "El Codito",
        "El Refugio de San Antonio",
        "El Verbenal",
        "Horizontes",
        "La Estrellita",
        "La Frontera",
        "La Llanurita",
        "Los Consuelos",
        "Marantá",
        "Maturín",
        "Medellín",
        "Mirador del Norte",
        "Nuevo Horizonte",
        "San Antonio Norte",
        "Santa Andersito",
        "Tibabita",
        "Viña del Mar",
        "Bosque de San Antonio",
        "Conjunto Camino del Palmar",
        "El Pite",
        "El Redil",
        "La Cita",
        "La Granja Norte",
        "La Uribe",
        "Los Naranjos",
        "San Juan Bosco",
        "Urbanización Los Laureles",
        "Ainsuca",
        "Alta Blanca",
        "Barrancas",
        "California",
        "Cerro Norte",
        "Danubio",
        "Don Bosco",
        "La Perla Oriental",
        "Las Areneras",
        "Milán (Barrancas)",
        "Pradera Norte",
        "San Cristóbal Norte",
        "San Cristóbal Norte parte alta",
        "San Cristóbal Norte parte baja",
        "Santa Teresa",
        "Soratama",
        "Torcoroma",
        "Villa Nydia",
        "Villa Oliva",
        "El Toberín",
        "Babilonia",
        "Darandelos",
        "Estrella del Norte",
        "Guanoa",
        "Jardín Norte",
        "La Liberia",
        "La Pradera Norte",
        "Las Orquídeas",
        "Pantanito",
        "Santa Mónica",
        "Villa Magdala",
        "Villas de Aranjuez",
        "Villas del Mediterráneo",
        "Zaragoza",
        "Acacias",
        "Antigua",
        "Belmira",
        "Bosque de Pinos",
        "Caobos Salazar",
        "Capri",
        "Cedritos",
        "Cedro Bolívar",
        "Cedro Golf",
        "Cedro Madeira",
        "Cedro Narváez",
        "Cedro Salazar",
        "El Contador",
        "El Rincón de Las Margaritas",
        "La Sonora",
        "Las Margaritas",
        "Lisboa",
        "Los Cedros",
        "Los Cedros Oriental",
        "Montearroyo",
        "Nueva Autopista",
        "Nuevo Country",
        "Sierras del Moral el Nogal",
        "Bella Suiza",
        "Bellavista",
        "Bosque Medina",
        "El Pañuelito",
        "El Pedregal",
        "Escuela de Caballería I",
        "Escuela de Infantería",
        "Francisco Miranda",
        "Ginebra",
        "La Esperanza",
        "La Glorieta",
        "Las Delicias del Carmen",
        "Sagrado Corazón",
        "San Gabriel",
        "Santa Ana",
        "Santa Ana Occidental",
        "Santa Bárbara",
        "Santa Bárbara Alta",
        "Santa Bárbara Oriental",
        "Unicerros",
        "Usaquén",
        "Country Club",
        "La Calleja",
        "La Carolina",
        "La Cristalina",
        "Prados del Country",
        "Recodo del Country",
        "Santa Coloma",
        "Soatama",
        "Toledo",
        "Torres del Country",
        "Vergel del Country",
        "Santa Bárbara Occidental",
        "Campo Alegre",
        "Molinos del Norte",
        "Multicentro",
        "Navarra",
        "Rincón del Chicó",
        "San Patricio",
        "Santa Bárbara",
        "Santa Bárbara Central",
        "Santa Bibiana",
        "Santa Paula"
      ];

      for (var i = 0; i < barriosUsaquen.length; i++) {
        var option = document.createElement("option");
        option.text = barriosUsaquen[i];
        option.value = barriosUsaquen[i].toLowerCase().replace(/\s/g, "_");
        barrios.add(option);
      }
    }else if (seleccionLocalidad === "Chapinero") {
        var barriosChapinero = [
          "Chicó Reservado",
          "Bellavista",
          "Chicó Alto",
          "El Nogal",
          "El Refugio",
          "La Cabrera",
          "Los Rosales",
          "Seminario",
          "Toscana",
          "La Esperanza Nororiental",
          "La Sureña",
          "San Isidro",
          "San Luis Altos del Cabo",
          "Bosque Calderón",
          "Bosque Calderón Tejada",
          "Chapinero Alto",
          "El Castillo",
          "El Paraíso",
          "Emaus",
          "Granada",
          "Ingemar",
          "Juan XXIII",
          "La Salle",
          "Las Acacias",
          "Los Olivos",
          "María Cristina",
          "Mariscal Sucre",
          "Nueva Granada",
          "Palomar",
          "Pardo Rubio",
          "San Martín de Porres",
          "Villa Anita",
          "Villa del Cerro",
          "Antiguo Country",
          "Chicó Norte",
          "Chicó Norte II",
          "Chicó Norte III",
          "Chicó Occidental",
          "El Chicó",
          "El Retiro",
          "Espartillal",
          "La Cabrera",
          "Lago Gaitán",
          "Porciúncula",
          "Quinta Camacho",
          "Cataluña",
          "Chapinero Central",
          "Chapinero Norte",
          "Marly",
          "Sucre"
        ];
    
        for (var i = 0; i < barriosChapinero.length; i++) {
          var option = document.createElement("option");
          option.text = barriosChapinero[i];
          option.value = barriosChapinero[i].toLowerCase().replace(/\s/g, "_");
          barrios.add(option);
        }
      }
}